### ISSUE TITLE
concourse 4.2.1 - web login is redirecting to 127.0.0.1

### ISSUE THREAD

**Issue by vaisyarajuraju** [concourse/concourse-docker#26]
I am running concourse latest version (from Docker-compose.yml) in a ubuntu 18.0.4 Server and I could access the concourse web UI after bringing up the docker-compose however on login, it redirect the the request to 127.0.0.1 instead of the actual ubuntu server IP. Is there any way to fix it by keeping the server IP instead of redirecting to local server IP 127.0.0.1

![](https://user-images.githubusercontent.com/28572787/46027224-54dd3280-c0bb-11e8-92bf-c90b78b7685c.png)

![](https://user-images.githubusercontent.com/28572787/46027236-5eff3100-c0bb-11e8-89f4-8dc88aa4b274.png)

**Comment by larssb** [comment]
Hi @vaisyarajuraju,

Are you sure that you have set the `--external-url` as described ind [Docker run installation](https://github.com/concourse/concourse-docker#docker-run)?
I think what you have done is likely that you wrote `http://localhost:8080` or `http://127.0.0.1:8080` in your docker-commpose.yml file or in the in `--external-url` environment variable to docker run. If you want the WEB-UI to go to your IP (192.168.1.18) ... that is what you should specify as the value to `--external-url`.

**Comment by kobylyanskiy** [comment]
I'm issuing this trouble too. Need to replace 127.0.0.1 with my server IP address to make everything work.

**Comment by jiaoyan2017** [comment]
Same issue. 
fly -t blu-ci login
logging in to team 'main'

navigate to the following URL in your browser:

  http://x.x.x.x:8080/sky/login?redirect_uri=http://127.0.0.1:38446/auth/callback

In browser, I'm also redirected to 127.0.0.1.

**Comment by larssb** [comment]
Try with a domainname, that works fine.

**Comment by dperezmavro** [comment]
Facing this problem here as well. In my case I am running concourse 4.2.2 on GKE and I need to provide the load-balancer IP for this parameter, which I don't know at the time of cluster creation (as the load balancer does not exist...).

Is there any default value that would tell concourse to use the server-ip instead?

**Comment by larssb** [comment]
Hi @mattskone ... exactly and thank you for trying it.

@dperezmavro, @vaisyarajuraju, @jiaoyan2017 and @kobylyanskiy please do that as well. Also, I'm sure that if you don't configure the ...EXTERNAL_URL... it will default to 127.0.0.1.

See:

```
The addition of the --external-url flag is not technically necessary, so if you're just testing things it's safe to omit it. Concourse uses it as a base when generating URLs to itself, so you won't want those to be the default http://127.0.0.1:8080 URL when you're developing on a different machine than the server.
```

From [Concourse setup docs](https://concourse-ci.org/install.html#quickstart) <-- it is actually clearly stated there.
So read-up on it >> try it out and come back and close the case when you have it working ;-).

**Comment by frankper** [comment]
Hi All 

I am trying to deploy  5.0.1 on Kubernetes using the upstream helm chart
External URL has been set correctly ( I can even see it in the web-pods as and ENV variable ) but when I try to authenticate using the cli I get a link 

`http://mydomain.com/sky/login?redirect_uri=http://127.0.0.1:54247/auth/callback`

**Comment by vito** [comment]
Closing as it sounds like a configuration issue. :+1:

**Comment by ajaysheoran2323** [comment]
where do I need to update this `--external-url` . I setup concourse using helm chart and I dont have `values.yaml` file.

**Comment by sanjaykmruk** [comment]
@ajaysheoran2323  you can create a values.yml file and set the value there as 

concourse:
  web:
    externalUrl: "external url"

and refer this value.yaml file on helm install command like this : helm install -f <path to values.yml file> stable/concourse
