### ISSUE TITLE
Unable to log in to the Concourse web page

### ISSUE THREAD

**Issue by karmicgeezer** [concourse/concourse-docker#43]
After a docker-compose up -d, the containers start, however when trying to login in (test/test) I get an HTTP 400 error.

From concourse-docker_web_1:

{"timestamp":"2019-05-01T09:31:31.300276529Z","level":"error","source":"atc","message":"atc.sky.callback.failed-to-fetch-cookie-state","data":{"error":"http: named cookie not present","session":"5.5"}

OS: macOS
Docker engine: 18.09.2

**Comment by vito** [comment]
Make sure you've accessed Concourse via the configured external URL - i.e. `localhost:8080` and not `127.0.0.1:8080`.
