### ISSUE TITLE
Running concourse-docker on CF/PCF

### ISSUE THREAD

**Issue by b3ccio** [concourse/concourse-docker#48]
Is there any documentation for running concourse-docker on CF or PCF? I need to sort out a few errors after a `cf push` including assigning the correct port and:
```[ERR] Please specify one command of: generate-key, land-worker, migrate, quickstart, retire-worker, web or worker``` Thanks.

**Comment by vito** [comment]
This is not supported. Concourse workers need a privileged container, which CF does not support.
