### ISSUE TITLE
quick start: web interface does not respond

### ISSUE THREAD

**Issue by smelc** [concourse/concourse-docker#49]
We're evaluating transitioning from [buildbot](http://buildbot.net/) to concourse but we could not get the [Quick Start](https://github.com/concourse/concourse/blob/master/README.md) to work.

Here's the steps I've done:

```
sudo apt install docker docker-compose
mkdir concourse
cd concourse
wget https://concourse-ci.org/docker-compose.yml
docker-compose up
Open 127.0.0.1:8080 in chrome (tried firefox too)
```

Both browsers do not fail immediately, there seems to be something at the endpoint:

```
< lsof -i tcp:8080
COMMAND  PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
chrome  3182 churlin   48u  IPv6 3014378      0t0  TCP ip6-localhost:43190->ip6-localhost:http-alt (ESTABLISHED)
chrome  3182 churlin   49u  IPv4 3006192      0t0  TCP localhost:53028->localhost:http-alt (ESTABLISHED)
```

but ultimately nothing shows up. I've attached the log of `docker-compose up`. I'm using Ubuntu 18.04, docker version is `18.09.5, build e8ff056`, docker-compose version is `1.17.1, build unknown`

[docker-compose-up-log.txt](https://github.com/concourse/concourse-docker/files/3359044/docker-compose-up-log.txt)

**Comment by smelc** [comment]
Anyone ? This is a bummer to evaluate concourse :-(

**Comment by vito** [comment]
:man_shrugging: I can only guess the root cause. We have a bunch of engineers using Docker Compose all day and haven't run into this. Wild guess: corporate firewall getting in the way? Maybe try `localhost:8080` instead?

You'd probably get more responses by asking in the [forums](https://discuss.concourse-ci.org/).

**Comment by smelc** [comment]
Retried after reading your comment and both 127.0.0.1:8080 and localhost:8080 are working.. Dang I had tried numerous times before creating the issue :-/ I must have missed something in the first place.. Sorry for the noise. I'll now evaluate moving from buildbot to concourse :-)

**Comment by vito** [comment]
Haha, no problem!
