### ISSUE TITLE
resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1 in resource

### ISSUE THREAD

**Issue by tomoyukim** [concourse/concourse-docker#55]
Hello.

I faced the following error in [github-pr-resource](https://github.com/telia-oss/github-pr-resource) resource on RancherOS with Portainer. There's no stderr output.

`resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1`

Previously, I ran concourse-docker with docker-compose on BargeOS with VirtualBox. Everything worked fine on the environment. 

I also found the below similar issue and tried to ran concourse-docker using docker-compose command purely without Portainer on clean RancherOS but the result was same.
https://github.com/concourse/concourse/issues/1489#issuecomment-324380237

I'm using concourse/concourse:5.3.3

Could you have any help for the issue?

**Comment by taylorsilva** [comment]
oof, this is super stale. Closing, we're on v7 now on Concourse. Post this in the main concourse/concourse repo if you're still having issues
https://github.com/concourse/concourse
