### ISSUE TITLE
Support service discovery via the magic `127.x.x.x` DNS server

### ISSUE THREAD

**Issue by vito** [concourse/concourse-docker#6]
Many many people have run into this. Docker Compose and various other magic-Docker-sauce runtimes set up a local DNS server to talk to other components (e.g. a Docker registry or other dependent service), but the address it wires in to the container (`127.0.0.11`) is not reachable from the container's network namespace. Nowadays Garden strips it out, which is an improvement as it won't resolve to the right address anyway, but it'd be nice if this Just Worked.

Is there something we can do, e.g. with https://wiki.archlinux.org/index.php/dnsmasq to forward DNS requests from the container to Docker's DNS server automatically?

Some context for this is in https://github.com/cloudfoundry/guardian/issues/42

**Comment by chendrix** [comment]
Moved to concourse/concourse#1145
