### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by antgrigorov** [concourse/concourse-docker#67]
I am using the concourse-docker on Mac and I am getting the error below as soon as I start a pipeline. Any suggestion how to solve it?

run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/concourse/docs/': Could not resolve host: github.com

Thanks!

**Comment by chenbh** [comment]
@antgrigorov this seems to be a problem with the latest git resource and Docker for Mac, I've wrote up an issue and workarounds at concourse/concourse#6038

**Comment by taylorsilva** [comment]
This has been resolved with newer versions of docker for mac
