### ISSUE TITLE
How to connect the worker to the web instance?

### ISSUE THREAD

**Issue by arulagrawal** [concourse/concourse-docker#78]
Running the given docker-compose.yml file after generating the keys on my local machine results in 
`worker_1  | {"timestamp":"2022-01-07T09:06:38.289690700Z","level":"info","source":"baggageclaim","message":"baggageclaim.using-driver","data":{"driver":"overlay"}}
worker_1  | {"timestamp":"2022-01-07T09:06:38.294664400Z","level":"info","source":"baggageclaim","message":"baggageclaim.listening","data":{"addr":"127.0.0.1:7788"}}
worker_1  | {"timestamp":"2022-01-07T09:06:38.299029000Z","level":"info","source":"worker","message":"worker.garden.dns-proxy.started","data":{"session":"1.2"}}
worker_1  | {"timestamp":"2022-01-07T09:06:38.299643400Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.failed-to-connect-to-tsa","data":{"error":"dial tcp 172.21.0.3:2222: connect: connection refused","session":"4.1"}}
worker_1  | {"timestamp":"2022-01-07T09:06:38.299787200Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.dial.failed-to-connect-to-any-tsa","data":{"error":"all worker SSH gateways unreachable","session":"4.1.1"}}
worker_1  | {"timestamp":"2022-01-07T09:06:38.299860800Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.failed-to-dial","data":{"error":"all worker SSH gateways unreachable","session":"4.1"}}
worker_1  | {"timestamp":"2022-01-07T09:06:38.299938900Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.exited-with-error","data":{"error":"all worker SSH gateways unreachable","session":"4.1"}}
worker_1  | {"timestamp":"2022-01-07T09:06:38.300243600Z","level":"error","source":"worker","message":"worker.beacon-runner.failed","data":{"error":"all worker SSH gateways unreachable","session":"4"}}`

How can I get the connection to work?

**Comment by Niceplace** [comment]
@arulagrawal were you able to solve your issue ? If yes can you post a solution ? I am trying to get setup for the first time using docker-compose and I am trying to find solutions. Cheers ! :)

**Comment by arulagrawal** [comment]
@Niceplace sorry to close without providing any info! I realized the same issue was mentioned in #74 and the fix there is what I needed as well
